---
name: IO-Stty
version: 0.03
author: []
abstract: lib/IO/Stty.pm
license: perl
resources:
  MailingList: mailto:toddr@cpan.org
  bugtracker: https://rt.cpan.org/NoAuth/Bugs.html?Dist=IO-Stty
  homepage: http://github.com/toddr/IO-Stty
  license: http://dev.perl.org/licenses/
  repository: git://github.com/toddr/IO-Stty.git
build_requires:
  Module::Build: 0.35
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  IO::Stty:
    file: lib/IO/Stty.pm
    version: 0.03
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
